# Generated by Django 3.0.4 on 2020-04-14 12:37

import core.managers
from django.db import migrations, models
import django.utils.timezone
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '유저', 'verbose_name_plural': '유저'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.managers.CustomModelManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='프로필 사진', upload_to=members.models.content_file_name),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='핸드폰 번호', max_length=13),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(help_text='파이어베이스 uid', max_length=28, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='닉네임', max_length=30, unique=True),
        ),
    ]
