# Generated by Django 3.0.4 on 2020-04-18 10:22

import core.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20200414_2137'),
        ('members', '0002_auto_20200414_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='media/avatars/carrot-default.png', help_text='프로필 사진', upload_to=members.models.content_file_name),
        ),
        migrations.CreateModel(
            name='SelectedLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('verified', models.BooleanField(default=False)),
                ('locate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Locate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', core.managers.CustomModelManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='selected_locations',
            field=models.ManyToManyField(help_text='내 동네 선택', through='members.SelectedLocation', to='location.Locate'),
        ),
    ]
