# Generated by Django 3.0.4 on 2020-04-18 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20200414_2137'),
        ('members', '0003_auto_20200418_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedlocation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_locations_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='selected_locations',
            field=models.ManyToManyField(help_text='내 동네 선택', related_name='users_select', through='members.SelectedLocation', to='location.Locate'),
        ),
    ]
