# Generated by Django 3.0.4 on 2020-04-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20200419_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedlocation',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
