# Generated by Django 3.0.4 on 2020-04-04 07:35

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20200402_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=members.models.content_file_name),
        ),
    ]
