# Generated by Django 3.0.4 on 2020-04-18 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20200414_2137'),
        ('members', '0005_selectedlocation_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedlocation',
            name='distance',
            field=models.ImageField(default=1000, upload_to=''),
        ),
        migrations.AlterField(
            model_name='selectedlocation',
            name='locate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_locations_verified', to='location.Locate'),
        ),
    ]
