# Generated by Django 3.0.4 on 2020-04-13 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20200407_1943'),
        ('members', '0006_auto_20200409_1444'),
    ]

    operations = [
    ]
