# Generated by Django 3.0.4 on 2020-04-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20200419_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedlocation',
            name='activated',
            field=models.BooleanField(default=False, help_text='선택된 동네'),
        ),
        migrations.AlterField(
            model_name='selectedlocation',
            name='distance',
            field=models.IntegerField(default=1000, help_text='동네 포함 범위'),
        ),
        migrations.AlterField(
            model_name='selectedlocation',
            name='verified',
            field=models.BooleanField(default=False, help_text='동네 인증 여부'),
        ),
    ]
