# Generated by Django 3.0.5 on 2020-04-26 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20200426_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selectedlocation',
            options={'verbose_name': '내 동네', 'verbose_name_plural': '내 동네'},
        ),
    ]
