# Generated by Django 3.0.4 on 2020-04-14 12:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locate',
            name='address',
            field=models.CharField(help_text='도로명 주소', max_length=100),
        ),
        migrations.AlterField(
            model_name='locate',
            name='dong',
            field=models.CharField(help_text='동 이름(i.g. 성수동)', max_length=20),
        ),
        migrations.AlterField(
            model_name='locate',
            name='gu',
            field=models.CharField(help_text='구 이름(i.g. 성동구)', max_length=20),
        ),
        migrations.AlterField(
            model_name='locate',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='위도', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='locate',
            name='latlng',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='위도 경도 좌표 객체', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='locate',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='경도', max_digits=12, null=True),
        ),
    ]
