# Generated by Django 3.0.4 on 2020-03-23 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('notice', '디지털/가전'), ('furniture', '가구/인테리어'), ('baby', '유아동/유아도서'), ('life', '생활/가공식품'), ('woman_wear', '여성의류'), ('woman_goods', '여성잡화'), ('beauty', '뷰티/미용'), ('male', '남성패션/잡화'), ('sports', '스포츠/레저'), ('game', '게임/취미'), ('book', '도서/티켓/음반'), ('pet', '반려동물용품'), ('other', '기타 중고물품'), ('buy', '삽니다')], max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('locate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Locate')),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글 목록',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/images')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
            ],
            options={
                'verbose_name': '이미지',
                'verbose_name_plural': '이미지 목록',
            },
        ),
    ]
