# Generated by Django 3.0.4 on 2020-03-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='showed_locate',
            field=models.ManyToManyField(related_name='showed_locate', to='location.Locate'),
        ),
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.CharField(choices=[('sales', '판매중'), ('reserve', '예약중'), ('end', '거래완료')], default='sales', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('digital', '디지털/가전'), ('furniture', '가구/인테리어'), ('baby', '유아동/유아도서'), ('life', '생활/가공식품'), ('woman_wear', '여성의류'), ('woman_goods', '여성잡화'), ('beauty', '뷰티/미용'), ('male', '남성패션/잡화'), ('sports', '스포츠/레저'), ('game', '게임/취미'), ('book', '도서/티켓/음반'), ('pet', '반려동물용품'), ('other', '기타 중고물품'), ('buy', '삽니다')], max_length=20),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
