# Generated by Django 3.0.4 on 2020-04-18 10:22

import core.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_auto_20200414_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchedWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(help_text='추천 검색어', max_length=100)),
                ('count', models.IntegerField(default=0, help_text='검색 횟수')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searched_words', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '검색어',
                'verbose_name_plural': '검색어 목록',
            },
            managers=[
                ('objects', core.managers.CustomModelManager()),
            ],
        ),
        migrations.DeleteModel(
            name='RecommendWord',
        ),
    ]
