# Generated by Django 3.0.4 on 2020-04-18 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_auto_20200418_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchedword',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searched_words', to=settings.AUTH_USER_MODEL),
        ),
    ]
