# Generated by Django 3.0.4 on 2020-04-09 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_postlike_recommendword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlike',
            old_name='user',
            new_name='author',
        ),
        migrations.AddField(
            model_name='postimage',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
