# Generated by Django 3.0.4 on 2020-04-09 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
        ('post', '0004_auto_20200407_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(help_text='Post Writer', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('digital', '디지털/가전'), ('furniture', '가구/인테리어'), ('baby', '유아동/유아도서'), ('life', '생활/가공식품'), ('woman_wear', '여성의류'), ('woman_goods', '여성잡화'), ('beauty', '뷰티/미용'), ('male', '남성패션/잡화'), ('sports', '스포츠/레저'), ('game', '게임/취미'), ('book', '도서/티켓/음반'), ('pet', '반려동물용품'), ('other', '기타 중고물품'), ('buy', '삽니다')], help_text='Post Category', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Post content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Post Created Time'),
        ),
        migrations.AlterField(
            model_name='post',
            name='locate',
            field=models.ForeignKey(help_text='Trade Area', on_delete=django.db.models.deletion.CASCADE, to='location.Locate'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=0, help_text='Goods Price'),
        ),
        migrations.AlterField(
            model_name='post',
            name='showed_locate',
            field=models.ManyToManyField(help_text='Group of Area to be shown', related_name='showed_locate', to='location.Locate'),
        ),
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.CharField(choices=[('sales', '판매중'), ('reserve', '예약중'), ('end', '거래완료')], default='sales', help_text='States of selling', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Post Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, help_text='Post Updated Time'),
        ),
        migrations.AlterField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(default=0, help_text='Post View Counts'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='photo',
            field=models.ImageField(help_text='Goods images', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='recommendword',
            name='content',
            field=models.CharField(help_text='Recommend Word', max_length=100),
        ),
        migrations.AlterField(
            model_name='recommendword',
            name='count',
            field=models.IntegerField(default=0, help_text='Searched Counts'),
        ),
    ]
