# Generated by Django 3.0.4 on 2020-04-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20200414_2137'),
        ('post', '0004_auto_20200418_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='showed_locate',
            field=models.ManyToManyField(help_text='보여질 지역', related_name='posts', to='location.Locate'),
        ),
    ]
