# Generated by Django 3.0.4 on 2020-04-20 11:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0005_auto_20200419_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='locate',
        ),
        migrations.AddField(
            model_name='post',
            name='like_users',
            field=models.ManyToManyField(related_name='like_post_set', through='post.PostLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
