# Generated by Django 3.0.4 on 2020-04-20 16:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0002_auto_20200414_2137'),
        ('post', '0006_auto_20200420_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_users',
            field=models.ManyToManyField(blank=True, help_text='관심 유저', related_name='like_post_set', through='post.PostLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='showed_locate',
            field=models.ManyToManyField(blank=True, help_text='보여질 지역', related_name='posts', to='location.Locate'),
        ),
    ]
