# Generated by Django 3.0.5 on 2020-04-23 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_like_users'),
        ('post', '0008_auto_20200421_1557'),
    ]

    operations = [
    ]
