# Generated by Django 3.0.5 on 2020-04-26 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0009_merge_20200423_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_users',
            field=models.ManyToManyField(blank=True, help_text='관심 유저', related_name='like_post_set', through='post.PostLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
