# Generated by Django 3.0.5 on 2020-04-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20200426_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(default='None', help_text='대표 거래 지역', max_length=200),
            preserve_default=False,
        ),
    ]
