# Generated by Django 3.0.5 on 2020-04-27 05:47

import core.managers
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_post_address'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='postlike',
            managers=[
                ('objects', core.managers.CustomModelManager()),
            ],
        ),
        migrations.AddField(
            model_name='postlike',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postlike',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='post',
            field=models.ForeignKey(help_text='게시글 번호', on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='post.Post'),
        ),
    ]
