# Generated by Django 3.0.4 on 2020-04-11 13:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('push_notifications', '0007_uniquesetting'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceOnUser',
            new_name='DeviceUser',
        ),
    ]
