# Generated by Django 3.0.4 on 2020-04-14 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0007_uniquesetting'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.CharField(help_text='알림 내용', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_succeed',
            field=models.BooleanField(default=False, help_text='알림 성공 여부'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noti_receiver', to='push_notifications.GCMDevice'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_sender', to='push_notifications.GCMDevice'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subtitle',
            field=models.CharField(blank=True, help_text='알림 부제목', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(help_text='알림 제목', max_length=200),
        ),
        migrations.DeleteModel(
            name='DeviceOnUser',
        ),
    ]
