# Generated by Django 3.0.4 on 2020-04-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20200414_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, help_text='알림 제목', max_length=200, null=True),
        ),
    ]
