# Generated by Django 3.0.4 on 2020-04-11 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0007_uniquesetting'),
        ('notification', '0002_auto_20200411_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noti_receiver', to='push_notifications.GCMDevice'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_sender', to='push_notifications.GCMDevice'),
        ),
        migrations.DeleteModel(
            name='DeviceUser',
        ),
    ]
