# Generated by Django 3.0.4 on 2020-04-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20200412_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.CharField(help_text='알림 내용', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_succeed',
            field=models.BooleanField(default=False, help_text='알림 성공 여부'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subtitle',
            field=models.CharField(blank=True, help_text='알림 부제목', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(help_text='알림 제목', max_length=200),
        ),
    ]
